apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: rook-ceph
spec:
  ingress:
  - action: Allow
    destination: {}
    source: {}
  order: 1000
  selector: projectcalico.org/orchestrator == 'k8s'
  types:
  - Ingress
